# Generated by Django 3.0.3 on 2020-09-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginAluno', models.CharField(max_length=15)),
                ('nomeAluno', models.CharField(max_length=50)),
                ('emailAluno', models.CharField(max_length=40)),
            ],
        ),
    ]
